package ro.orange.uber.entities;

public enum PaymentStatus {
    CREATED, STATUS_AUTHORIZED_PENDING, STATUS_AUTHORIZED, STATUS_AUTHORIZED_FAILED, STATUS_CONFIRMED_PENDING, STATUS_CONFIRMED, STATUS_CONFIRMED_FAILED, STATUS_CANCELLED
}
